apiVersion: v1
kind: Service
metadata:
  name: property-service
  namespace: derent
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: property-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  namespace: derent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
        - name: property-service
          image: medgm/real-estate-property-service:pricing-fix
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: derent-config
                  key: spring-datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: derent-config
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: derent-secrets
                  key: postgres-password
            - name: AWS_KEY
              value: "dummy-key"
            - name: AWS_SECRET_KEY
              value: "dummy-secret"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_BUCKET_NAME
              value: "derent-bucket"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: PRICING_API_URL
              value: "http://pricing-api:8000"
            - name: USER_SERVICE_URL
              value: "http://user-service:8082"
            - name: BOOKING_SERVICE_URL
              value: "http://booking-service:8083"
