apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: derent
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: booking-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: derent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: medgm/real-estate-booking-service:urls-fix
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: derent-config
                  key: spring-datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: derent-config
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: derent-secrets
                  key: postgres-password
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: PROPERTY_SERVICE_URL
              value: "http://property-service:8081"
            - name: USER_SERVICE_URL
              value: "http://user-service:8082"
