apiVersion: v1
kind: ConfigMap
metadata:
  name: derent-config
  namespace: derent
data:
  postgres-db: "derentdb"
  postgres-user: "postgres"
  spring-datasource-url: "jdbc:postgresql://postgres-service:5432/derentdb"
  rabbitmq-host: "rabbitmq-service"
  rabbitmq-port: "5672"

